# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  identifier = "search"
  weight = 50
  [main.params]
    action = "search"

[[main]]
  name = "GitHub"
  url = "https://github.com/stkrizh/stanislavtech"
  weight = 60
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "appearance"
  weight = 70
  [main.params]
    action = "appearance"
    showName = false

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Articles"
  pageRef = "articles"
  weight = 10

# [[footer]]
#  name = "TIL"
#  pageRef = "til"
#  weight = 15

[[footer]]
  name = "Book Reviews"
  pageRef = "book-reviews"
  weight = 20

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 30
