# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "custom"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

defaultThemeColor = "#FFFFFF"

enableSearch = true
enableCodeCopy = false
enableImageLazyLoading = true
enableImageWebp = true

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
  layout = "hybrid" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  # logoDark = "img/dark-logo.jpg"
  showTitle = true

[footer]
  showCopyright = false
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 10

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/stkrizh/stanislavtech/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  # sharingLinks = ["x-twitter", "bluesky", "mastodon", "facebook", "reddit", "linkedin", "telegram",]

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showTaxonomies = true
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
